services:
  node:
    container_name: node
    build:
      context: ./node
    ports:
      - "8001:8001"
    volumes:
      - ./node:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile.db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=fc-node-db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:

networks:
  app-network:
    driver: bridge