FROM node:23-alpine

# Create app directory
WORKDIR /usr/src/app

ADD package.json package-lock.json tsconfig.json ./

RUN npm install

COPY src ./src

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]